name: Local Config
version: 1.0.0
schema: v1


name: Local Config
version: 1.0.0
schema: v1
models:
  - name: Gemini 2.5 Pro
    provider: gemini
    model: gemini-2.5-pro
    apiKey: AIzaSyDtrnl1_4VjI01KI6mOnl9xNyaEuaKaFak
  - name: Gemini 2.0 Flash
    provider: gemini
    model: gemini-2.0-flash
    apiKey: AIzaSyDtrnl1_4VjI01KI6mOnl9xNyaEuaKaFak

